---
- name: Set one-time boot device to {{ bootdevice }}
  community.general.redfish_command:
    category: Systems
    command: SetOneTimeBoot
    bootdevice: "{{ bootdevice }}"
    baseuri: "{{ baseuri }}:443"
    username: "{{ username }}"
    password: "{{ password }}"
    timeout: 20

- name: Ensure server is powered on
  community.general.redfish_command:
    category: Systems
    command: PowerOn
    baseuri: "{{ baseuri }}:443"
    username: "{{ username }}"
    password: "{{ password }}"


- name: Reboot server
  community.general.redfish_command:
    category: Systems
    command: PowerForceRestart
    baseuri: "{{ baseuri }}:443"
    username: "{{ username }}"
    password: "{{ password }}"
    timeout: 20
